"""Monte Carlo GO × Taxonomy enrichment analysis.

This module implements single-sample enrichment testing for DIA-based
peptide abundance data using empirical null distributions generated by
Monte Carlo randomization.

Two complementary shuffle modes are supported:

- **Taxonomy Shuffle** (aspect-stratified): keep peptide GO assignments
  fixed, randomize peptide taxonomy assignments.  For each GO aspect
  (molecular_function, biological_process, cellular_component), the
  shuffle pool is restricted to peptides that have at least one GO
  term in that aspect.  This prevents spurious enrichment of GO root
  terms caused by cross-aspect annotation-quality differences.
- **GO Shuffle** (aspect-stratified): keep peptide taxonomy assignments
  fixed, independently randomize peptide GO assignments within each GO
  aspect (molecular_function, biological_process, cellular_component).
  Tests whether a taxon is unusually enriched/depleted for a GO term,
  controlling for cross-aspect annotation-quality confounds.

Both modes produce two-sided empirical p-values.  Benjamini-Hochberg
FDR correction is applied to produce q-values.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from typing import TYPE_CHECKING

import numpy as np
from numpy.typing import NDArray

if TYPE_CHECKING:
    from metagomics2.core.aggregation import AggregationResult, ComboAggregate
    from metagomics2.core.annotation import PeptideAnnotation

logger = logging.getLogger(__name__)

# Small constant for numerical stability in log2 enrichment
DEFAULT_EPS = 1e-10


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def compute_enrichment_pvalues(
    annotations: list[PeptideAnnotation],
    aggregation: AggregationResult,
    combos: dict[tuple[int, str], ComboAggregate],
    iterations: int = 1000,
    threads: int = 1,
    eps: float = DEFAULT_EPS,
    seed: int | None = None,
    go_namespaces: dict[str, str] | None = None,
) -> None:
    """Run both shuffle modes and populate p/q-values on *combos* in place.

    Args:
        annotations: Peptide annotations for the sample.
        aggregation: Pre-computed aggregation result.
        combos: Dictionary of (tax_id, go_id) → ComboAggregate.
            Updated **in place** with p-value and q-value fields.
        iterations: Number of Monte Carlo iterations.
        threads: Number of parallel workers (accepted but currently unused).
        eps: Epsilon for numerical stability.
        seed: Optional RNG seed for reproducibility.
        go_namespaces: Mapping from GO term ID to namespace string
            (e.g. ``{"GO:0003674": "molecular_function", ...}``).
            Used for aspect-stratified GO shuffling.  If ``None``,
            GO closures are shuffled as a single atomic unit (legacy
            behaviour, not recommended).
    """
    if not combos:
        return

    # Filter to annotated peptides with both taxonomy and GO assignments
    ann_list = [
        a for a in annotations
        if a.is_annotated and a.taxonomy_nodes and a.go_terms
    ]
    if not ann_list:
        return

    # Build index mappings
    idx = _build_index_maps(ann_list, combos, go_namespaces=go_namespaces)
    if idx.n_pairs == 0:
        return

    aspect_stratified = go_namespaces is not None
    logger.info(
        "Running enrichment: %d peptides, %d taxa, %d GO terms, %d tested pairs, "
        "%d iterations, aspect-stratified=%s",
        idx.n_peptides, idx.n_taxa, idx.n_go, idx.n_pairs, iterations,
        aspect_stratified,
    )

    # --- Taxonomy shuffle (p-value for GO within taxon) ---
    # When aspect-stratified, run a separate shuffle per GO aspect so
    # the shuffle pool for each GO term only includes peptides that
    # have at least one GO term in that aspect.  This prevents root
    # terms from appearing enriched due to cross-aspect annotation
    # quality differences.
    if aspect_stratified:
        pvals_tax = _run_taxonomy_shuffle_per_aspect(
            ann_list, combos, go_namespaces, iterations=iterations,
            eps=eps, seed=seed,
        )
    else:
        pvals_tax = _run_shuffle(
            idx, mode="taxonomy", iterations=iterations,
            eps=eps, seed=seed,
        )

    # --- GO shuffle (p-value for taxon within GO) ---
    pvals_go = _run_shuffle(
        idx, mode="go", iterations=iterations,
        eps=eps, seed=seed,
    )

    # BH correction (across ALL tested pairs, both modes)
    qvals_tax = benjamini_hochberg(pvals_tax)
    qvals_go = benjamini_hochberg(pvals_go)

    # Write back to combos
    for i, key in enumerate(idx.pair_keys):
        combo = combos[key]
        combo.pvalue_go_for_taxon = float(pvals_tax[i])
        combo.pvalue_taxon_for_go = float(pvals_go[i])
        combo.qvalue_go_for_taxon = float(qvals_tax[i])
        combo.qvalue_taxon_for_go = float(qvals_go[i])

    logger.info("Enrichment analysis complete.")


def _run_taxonomy_shuffle_per_aspect(
    ann_list: list[PeptideAnnotation],
    combos: dict[tuple[int, str], ComboAggregate],
    go_namespaces: dict[str, str],
    iterations: int,
    eps: float,
    seed: int | None,
) -> NDArray[np.float64]:
    """Run taxonomy shuffle separately for each GO aspect.

    For each aspect (MF, BP, CC), the shuffle pool is restricted to
    peptides that have at least one GO term in that aspect.  This
    ensures the background proportion ``p_bg`` is computed relative
    to peptides with the relevant annotation, not all annotated
    peptides.  Tested pairs are grouped by the GO term's namespace
    and each group is shuffled independently.

    Returns an array of p-values aligned to the *full* ``pair_keys``
    order from the master ``_IndexMaps`` built on the complete
    ``ann_list``.
    """
    # Build the master index maps to get the canonical pair_keys order
    master_idx = _build_index_maps(ann_list, combos, go_namespaces=go_namespaces)
    n_pairs = master_idx.n_pairs
    pvalues = np.ones(n_pairs, dtype=np.float64)  # default: non-significant

    if n_pairs == 0:
        return pvalues

    # Map each pair key → its index in the master pair_keys list
    pair_key_to_master_idx = {k: i for i, k in enumerate(master_idx.pair_keys)}

    # Group tested pairs by GO term aspect
    aspect_pairs: dict[str, list[tuple[int, str]]] = {}
    for key in master_idx.pair_keys:
        _tax_id, go_id = key
        ns = go_namespaces.get(go_id, "unknown")
        aspect_pairs.setdefault(ns, []).append(key)

    # Group peptides by which aspects they contribute to
    aspect_peptide_sets: dict[str, set[int]] = {}
    for p, ann in enumerate(ann_list):
        for go_id in ann.go_terms:
            ns = go_namespaces.get(go_id, "unknown")
            aspect_peptide_sets.setdefault(ns, set()).add(p)
    # Convert sets to sorted lists
    aspect_peptides: dict[str, list[int]] = {
        ns: sorted(peps) for ns, peps in aspect_peptide_sets.items()
    }

    for ns, pairs_in_aspect in aspect_pairs.items():
        pep_indices = aspect_peptides.get(ns)
        if not pep_indices or len(pep_indices) < 2:
            continue

        # Build restricted annotation list and combos for this aspect
        restricted_anns = [ann_list[p] for p in pep_indices]
        restricted_combos = {k: combos[k] for k in pairs_in_aspect if k in combos}

        if not restricted_combos:
            continue

        # Build index maps on the restricted pool
        restricted_idx = _build_index_maps(restricted_anns, restricted_combos)
        if restricted_idx.n_pairs == 0:
            continue

        logger.info(
            "Taxonomy shuffle for %s: %d peptides, %d pairs",
            ns, restricted_idx.n_peptides, restricted_idx.n_pairs,
        )

        # Run taxonomy shuffle on the restricted pool
        aspect_pvals = _run_shuffle(
            restricted_idx, mode="taxonomy", iterations=iterations,
            eps=eps, seed=seed,
        )

        # Map results back to master pair order
        for j, key in enumerate(restricted_idx.pair_keys):
            master_i = pair_key_to_master_idx.get(key)
            if master_i is not None:
                pvalues[master_i] = aspect_pvals[j]

    return pvalues


def benjamini_hochberg(pvalues: NDArray[np.float64]) -> NDArray[np.float64]:
    """Benjamini-Hochberg FDR correction.

    Args:
        pvalues: 1-D array of raw p-values.

    Returns:
        Array of q-values (adjusted p-values), same length.
    """
    n = len(pvalues)
    if n == 0:
        return np.array([], dtype=np.float64)

    # Sort p-values (ascending) and track original order
    order = np.argsort(pvalues)
    sorted_p = pvalues[order]

    # BH adjustment: q_i = min(p_i * n / rank, 1.0), enforced monotonic
    ranks = np.arange(1, n + 1, dtype=np.float64)
    adjusted = np.minimum(sorted_p * n / ranks, 1.0)

    # Enforce monotonicity (backward cumulative minimum)
    for i in range(n - 2, -1, -1):
        adjusted[i] = min(adjusted[i], adjusted[i + 1])

    # Restore original order
    qvalues = np.empty(n, dtype=np.float64)
    qvalues[order] = adjusted
    return qvalues


# ---------------------------------------------------------------------------
# Internal data structures
# ---------------------------------------------------------------------------


@dataclass
class _IndexMaps:
    """Integer-indexed representations for fast Monte Carlo iteration."""

    n_peptides: int
    n_taxa: int
    n_go: int
    n_pairs: int

    # Peptide abundance vector  shape (P,)
    abundance: NDArray[np.float64]

    # Boolean membership matrices  shape (P, T) and (P, G)
    # Stored as dense bool arrays; for very large datasets a sparse
    # representation would be more memory-efficient.
    tax_mem: NDArray[np.bool_]
    go_mem: NDArray[np.bool_]

    # Mapping from internal pair index → original combo key
    pair_keys: list[tuple[int, str]]

    # Pair membership as index arrays for efficient slicing
    pair_tax_idx: NDArray[np.intp]   # shape (n_pairs,) — tax column index for each pair
    pair_go_idx: NDArray[np.intp]    # shape (n_pairs,) — GO column index for each pair

    # Observed statistics for tested pairs
    obs_log2: NDArray[np.float64]    # shape (n_pairs,)

    # Aspect-stratified GO column masks for independent shuffling.
    # List of boolean arrays, each shape (G,), indicating which GO columns
    # belong to each aspect.  None when namespace info is unavailable.
    go_aspect_masks: list[NDArray[np.bool_]] | None = None


def _build_index_maps(
    ann_list: list[PeptideAnnotation],
    combos: dict[tuple[int, str], ComboAggregate],
    go_namespaces: dict[str, str] | None = None,
) -> _IndexMaps:
    """Convert annotations and combos into integer-indexed arrays."""

    # Collect unique taxa and GO terms referenced by the combos
    combo_taxa: set[int] = set()
    combo_go: set[str] = set()
    for tax_id, go_id in combos:
        combo_taxa.add(tax_id)
        combo_go.add(go_id)

    # Also include taxa and GO terms from annotations (needed for proper shuffling)
    for ann in ann_list:
        combo_taxa.update(ann.taxonomy_nodes)
        combo_go.update(ann.go_terms)

    tax_list = sorted(combo_taxa)
    go_list = sorted(combo_go)
    tax_to_idx = {t: i for i, t in enumerate(tax_list)}
    go_to_idx = {g: i for i, g in enumerate(go_list)}

    n_pep = len(ann_list)
    n_tax = len(tax_list)
    n_go = len(go_list)

    abundance = np.array([a.quantity for a in ann_list], dtype=np.float64)
    tax_mem = np.zeros((n_pep, n_tax), dtype=np.bool_)
    go_mem = np.zeros((n_pep, n_go), dtype=np.bool_)

    for p, ann in enumerate(ann_list):
        for t in ann.taxonomy_nodes:
            if t in tax_to_idx:
                tax_mem[p, tax_to_idx[t]] = True
        for g in ann.go_terms:
            if g in go_to_idx:
                go_mem[p, go_to_idx[g]] = True

    # Compute marginal abundances first (needed for pair filtering)
    eps = DEFAULT_EPS
    a_total = float(abundance.sum())
    a_tax = tax_mem.T @ abundance   # (T,)
    a_go = go_mem.T @ abundance     # (G,)

    # Build pair arrays — only for combos that exist and have positive
    # marginal abundances (A_TAX > 0 and A_GO > 0).  Pairs with zero
    # marginals would produce degenerate log2 enrichment values driven
    # entirely by the epsilon constant.
    pair_keys: list[tuple[int, str]] = []
    pair_tax: list[int] = []
    pair_go: list[int] = []

    for key in combos:
        tax_id, go_id = key
        if tax_id in tax_to_idx and go_id in go_to_idx:
            ti = tax_to_idx[tax_id]
            gi = go_to_idx[go_id]
            if a_tax[ti] > 0 and a_go[gi] > 0:
                pair_keys.append(key)
                pair_tax.append(ti)
                pair_go.append(gi)

    pair_tax_idx = np.array(pair_tax, dtype=np.intp)
    pair_go_idx = np.array(pair_go, dtype=np.intp)

    # A_JOINT via weighted membership: diag(abundance) @ tax_mem → (P, T)
    weighted_tax = tax_mem * abundance[:, None]   # broadcast multiply
    joint_matrix = weighted_tax.T @ go_mem         # (T, G)

    # Vectorized observed log2 enrichment for all tested pairs
    joint_vals = joint_matrix[pair_tax_idx, pair_go_idx]  # (n_pairs,)
    a_t_vals = a_tax[pair_tax_idx]                         # (n_pairs,)
    a_g_vals = a_go[pair_go_idx]                           # (n_pairs,)
    p_obs = (joint_vals + eps) / (a_t_vals + eps)
    p_bg = (a_g_vals + eps) / (a_total + eps)
    obs_log2 = np.log2(p_obs / p_bg)

    # Build per-aspect column masks for aspect-stratified GO shuffling
    go_aspect_masks: list[NDArray[np.bool_]] | None = None
    if go_namespaces is not None:
        aspects_seen: dict[str, list[int]] = {}
        for j, go_id in enumerate(go_list):
            ns = go_namespaces.get(go_id, "unknown")
            aspects_seen.setdefault(ns, []).append(j)

        go_aspect_masks = []
        for ns in sorted(aspects_seen):
            mask = np.zeros(n_go, dtype=np.bool_)
            for j in aspects_seen[ns]:
                mask[j] = True
            go_aspect_masks.append(mask)

        logger.info(
            "Aspect-stratified GO shuffle: %d aspects (%s)",
            len(go_aspect_masks),
            ", ".join(f"{ns}: {len(cols)} terms" for ns, cols in sorted(aspects_seen.items())),
        )

    return _IndexMaps(
        n_peptides=n_pep,
        n_taxa=n_tax,
        n_go=n_go,
        n_pairs=len(pair_keys),
        abundance=abundance,
        tax_mem=tax_mem,
        go_mem=go_mem,
        pair_keys=pair_keys,
        pair_tax_idx=pair_tax_idx,
        pair_go_idx=pair_go_idx,
        obs_log2=obs_log2,
        go_aspect_masks=go_aspect_masks,
    )


# ---------------------------------------------------------------------------
# Monte Carlo iteration
# ---------------------------------------------------------------------------


def _run_shuffle(
    idx: _IndexMaps,
    mode: str,
    iterations: int,
    eps: float,
    seed: int | None,
) -> NDArray[np.float64]:
    """Run Monte Carlo shuffle in a single process and return two-sided
    empirical p-values.

    All inner loops are fully vectorized with NumPy fancy indexing —
    there are no Python per-pair ``for`` loops.  The matrix operations
    (``@``) use BLAS internally and are already multi-threaded.

    Args:
        idx: Pre-built index maps.
        mode: ``"taxonomy"`` or ``"go"``.
        iterations: Total number of Monte Carlo iterations.
        eps: Epsilon for numerical stability.
        seed: Optional RNG seed for reproducibility.

    Returns:
        Array of two-sided p-values, one per tested pair.
    """
    rng = np.random.default_rng(seed)
    n_pairs = idx.n_pairs

    # Pre-compute quantities that stay fixed
    abundance = idx.abundance
    a_total = float(abundance.sum())
    pair_tax = idx.pair_tax_idx
    pair_go = idx.pair_go_idx

    if mode == "taxonomy":
        fixed_mem = idx.go_mem
        shuffle_mem = idx.tax_mem.copy()
        a_fixed = fixed_mem.T @ abundance  # A_GO, shape (G,) — stays fixed
    else:
        fixed_mem = idx.tax_mem
        shuffle_mem = idx.go_mem.copy()
        a_fixed = fixed_mem.T @ abundance  # A_TAX, shape (T,) — stays fixed

    # Pre-compute weighted fixed side (only needed for GO shuffle mode)
    if mode == "go":
        weighted_fixed = fixed_mem * abundance[:, None]  # (P, T)

    # Store all null statistics to compute two-sided p-values afterwards
    null_values = np.empty((iterations, n_pairs), dtype=np.float64)

    # For aspect-stratified GO shuffle: pre-extract per-aspect sub-matrices
    aspect_submats: list[NDArray[np.bool_]] | None = None
    if mode == "go" and idx.go_aspect_masks is not None:
        aspect_submats = [shuffle_mem[:, mask] for mask in idx.go_aspect_masks]

    for b in range(iterations):
        if mode == "taxonomy":
            perm = rng.permutation(idx.n_peptides)
            shuffled = shuffle_mem[perm]
            weighted_shuffled = shuffled * abundance[:, None]
            joint_matrix = weighted_shuffled.T @ fixed_mem  # (T, G)
            a_shuffled = shuffled.T @ abundance             # (T,)
            joint_vals = joint_matrix[pair_tax, pair_go]
            denom_vals = a_shuffled[pair_tax]
            bg_vals = a_fixed[pair_go]
        elif aspect_submats is not None:
            # Aspect-stratified GO shuffle: independent permutation per
            # aspect.  Peptides that lack any term in an aspect keep
            # their empty row — they do NOT gain terms from other
            # peptides.  Only peptides that have ≥1 term in the aspect
            # participate in that aspect's shuffle.
            shuffled = np.empty_like(shuffle_mem)
            for aspect_mask, aspect_submat in zip(idx.go_aspect_masks, aspect_submats):
                has_aspect = aspect_submat.any(axis=1)  # (P,) bool
                has_idx = np.where(has_aspect)[0]
                if len(has_idx) < 2:
                    shuffled[:, aspect_mask] = aspect_submat
                    continue
                result = aspect_submat.copy()
                perm = rng.permutation(len(has_idx))
                result[has_idx] = aspect_submat[has_idx[perm]]
                shuffled[:, aspect_mask] = result
            joint_matrix = weighted_fixed.T @ shuffled   # (T, G)
            a_shuffled = shuffled.T @ abundance          # (G,)
            joint_vals = joint_matrix[pair_tax, pair_go]
            denom_vals = a_fixed[pair_tax]
            bg_vals = a_shuffled[pair_go]
        else:
            # Legacy: shuffle entire GO closure as one unit
            perm = rng.permutation(idx.n_peptides)
            shuffled = shuffle_mem[perm]
            joint_matrix = weighted_fixed.T @ shuffled   # (T, G)
            a_shuffled = shuffled.T @ abundance          # (G,)
            joint_vals = joint_matrix[pair_tax, pair_go]
            denom_vals = a_fixed[pair_tax]
            bg_vals = a_shuffled[pair_go]

        p_obs_null = (joint_vals + eps) / (denom_vals + eps)
        p_bg = (bg_vals + eps) / (a_total + eps)
        null_values[b] = np.log2(p_obs_null / p_bg)

    # Two-sided empirical p-values
    mean_null = null_values.mean(axis=0)                         # (n_pairs,)
    obs_dev = np.abs(idx.obs_log2 - mean_null)                   # (n_pairs,)
    null_dev = np.abs(null_values - mean_null[None, :])          # (B, n_pairs)
    count_extreme = np.sum(null_dev >= obs_dev[None, :], axis=0) # (n_pairs,)

    pvalues = (1.0 + count_extreme.astype(np.float64)) / (iterations + 1.0)
    return pvalues
